### ISSUE TITLE
ES8266 Module Typo's

### ISSUE THREAD

**Issue by will2055** [sparkfun/Graphical_Datasheets#3]
List of current typo's:

- The default baud rate should be 115200 (not 11520)
- In the asterisk footnote, mileage is misspelled (currently spelled milage)

**Comment by bboyho** [comment]
Fixed in this commit => https://github.com/sparkfun/Graphical_Datasheets/commit/e6fc46a40c41a79f9953b074768fbd0025f10a35

Just need to update links on product pages and tutorial.

**Comment by bboyho** [comment]
Updated
