### ISSUE TITLE
GraphicalDatasheet-SamD21TurboDev.pdf should show RX_LED attached to pin PA31 not PB03

### ISSUE THREAD

**Issue by sdward-github** [sparkfun/Graphical_Datasheets#4]
GraphicalDatasheet-SamD21TurboDev.pdf should show RX_LED attached to pin PA31 not PB03. Schematic file shows RX_LED attached to pin PA31.

**Comment by bboyho** [comment]
Hi,

Sorry for the delay in reply. Looking further at the datasheet, it appears that the other cell labels are also incorrect. I'll need to get back into the file and update the pin characteristics as well before reuploading to the product page, tutorial, and GitHub repo.

**Comment by sdward-github** [comment]
Very good. I'll watch for the update.

**Comment by bboyho** [comment]
Links are updated on the product page and tutorial. Changes have been pushed to their respective repositories. =)

**Comment by sdward-github** [comment]
Thank!
